(defun aoc-day4-1 (input)
  (let ((num-correct-passphrases 0))
    (dolist (passphrase input)
      (let ((words (split-string passphrase " ")))
        (when (= (length words)
                 (length (delete-dups words)))
          (incf num-correct-passphrases))))
    num-correct-passphrases))

(defun aoc-sort-string (str)
  (apply #'string (sort (string-to-list str) #'<)))

(defun aoc-day4-2 (input)
  (let ((num-correct-passphrases 0))
    (dolist (passphrase input)
      (let ((words (mapcar #'aoc-sort-string (split-string passphrase " "))))
        (when (= (length words)
                 (length (delete-dups words)))
          (incf num-correct-passphrases))))
    num-correct-passphrases))
